# Site Info
title: '두루미현의 개발일찌'
tagline: '두루미현의 개발일찌'
description: '마케팅과 프로그래밍 공부일지와 느낀점을 기록합니다.
baseurl: "/"
url: http://durumimi.github.io
logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fk.kakaocdn.net%2Fdn%2FbnwsZW%2FbtqDmmFtoQi%2Fhkni3JlyOkRspQoKROC3j0%2Fimg.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Durumi_hyun
  description: 쥬니어개발자의 성장기 (Durumihyun)
  contact:
    # linkedin:  https://www.linkedin.com/in/xx
    github:    https://github.com/durumimi
    facebook:   https://www.facebook.com/durumihyun
    # twitter:   https://twitter.com/Li_Zhihao
    # weibo:     http://weibo.com/41173780
    email:     mailto:fisinbi2@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/blog/'
  Categories:           
   - '/'
    # - { Categories All: '/blog/categories/' }
    - { TIL (Today I Learned): '/blog/categories/#til' }
    - { javascript: '/blog/categories/#javascript' }
    - { 알고리즘 문제풀이: '/blog/categories/#알고리즘-문제풀이' }
    - { etc: '/blog/categories/#etc' }
    # - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
      Search:
    - '/search/'


# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'your_short_name' # leave blank if you don't want disqus


# Use the following plug-ins
gems:
  - jekyll-paginate